# -*- coding: utf-8 -*-

# Define here the models for your scraped items
#
# See documentation in:
# https://docs.scrapy.org/en/latest/topics/items.html

import scrapy


class GonggaoItem(scrapy.Item):
    grab_time = scrapy.Field()
    url = scrapy.Field()
    status = scrapy.Field()

    category = scrapy.Field()
    batch = scrapy.Field()
    serial_number = scrapy.Field()
    company = scrapy.Field()
    type = scrapy.Field()
    vehicle_model = scrapy.Field()
    name = scrapy.Field()
    mileage = scrapy.Field()
    car_quality = scrapy.Field()
    battery_quality = scrapy.Field()
    battery_energy = scrapy.Field()
    remarks = scrapy.Field()

    fuel_consumption = scrapy.Field()
    engine_displacement = scrapy.Field()

    change_record = scrapy.Field()
    # name = scrapy.Field()
    announcement_model = scrapy.Field()
    # batch = scrapy.Field()
    brand = scrapy.Field()
    # type = scrapy.Field()
    rated_quality = scrapy.Field()
    # car_quality = scrapy.Field()
    readiness_quality = scrapy.Field()
    fuel_type = scrapy.Field()
    emissions_standards = scrapy.Field()
    axis = scrapy.Field()
    wheelbase = scrapy.Field()
    axle_load = scrapy.Field()
    spring_sheet = scrapy.Field()
    tires = scrapy.Field()
    tire_specifications = scrapy.Field()
    departure_angle = scrapy.Field()
    overhang = scrapy.Field()
    front_track = scrapy.Field()
    rear_track = scrapy.Field()
    identification = scrapy.Field()
    vehicle_length = scrapy.Field()
    vehicle_width = scrapy.Field()
    vehicle_height = scrapy.Field()
    cargo_length = scrapy.Field()
    cargo_width = scrapy.Field()
    cargo_height = scrapy.Field()
    maximum_speed = scrapy.Field()
    rated_capacity = scrapy.Field()
    cab_ride = scrapy.Field()
    steering_type = scrapy.Field()
    totalmass_trailer_quality = scrapy.Field()
    load_weight_use_factor = scrapy.Field()
    maximum_loading_mass_saddle_trailer = scrapy.Field()
    # company = scrapy.Field()
    company_address = scrapy.Field()
    phone = scrapy.Field()
    fax = scrapy.Field()
    postal = scrapy.Field()
    chassis_1 = scrapy.Field()
    chassis_2 = scrapy.Field()
    chassis_3 = scrapy.Field()
    chassis_4 = scrapy.Field()
    engine_model = scrapy.Field()
    engine_anufacturer = scrapy.Field()
    engine_trademark = scrapy.Field()
    # engine_displacement = scrapy.Field()
    engine_power = scrapy.Field()
    remark = scrapy.Field()
